[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
JSON3 = "1"
PrettyTables = "3"
julia = "1.11"

[workspace]
projects = ["nn", "misc", "polybench"]
