[deps]
Boltz = "4544d5e4-abc5-4dea-817f-29e4c205d9c8"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Reactant_jll = "0192cb87-2b54-54ad-80e0-3be72ad8a3c0"

[sources]
Reactant = {path = ".."}

[compat]
Boltz = "1.7"
Chairmarks = "1"
Enzyme = "0.13.73"
JSON3 = "1"
LinearAlgebra = "1.10"
Lux = "1.21"
NeuralOperators = "0.6.2"
PrecompileTools = "1.2"
Printf = "1.10"
Reactant = "0.2.161"
julia = "1.11"
