[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
JSON = "1"
PrettyTables = "3"
julia = "1.11"

[workspace]
projects = ["nn", "misc", "polybench", "comrade", "oceananigans"]
