[project]
name = "sampling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.12"
dependencies = [
    "blackjax>=1.3",
    "ipython>=8.38.0",
    "jax[cuda12]==0.5.0",
]
