[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Comrade = "99d987ce-9a1e-4df8-bc0b-1ea019aa547b"
ComradeBase = "6d8c423b-a35f-4ef1-850c-862fe21f82c4"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pyehtim = "3d61700d-6e5b-419a-8e22-9c066cf00468"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
VLBIImagePriors = "b1ba175b-8447-452c-b961-7db2d6f7a029"
VLBILikelihoods = "90db92cd-0007-4c0a-8e51-dbf0782ce592"
VLBISkyModels = "d6343c73-7174-4e0f-bb64-562643efbeca"

[sources.Comrade]
rev = "ptiede-reactant"
url = "https://github.com/ptiede/Comrade.jl"

[sources.ComradeBase]
rev = "main"
url = "https://github.com/ptiede/ComradeBase.jl"

[sources.NFFT]
rev = "ptiede-reactant"
url = "https://github.com/ptiede/NFFT.jl"

[sources.Reactant]
path = "../../"

[sources.TransformVariables]
rev = "ptiede-reactant"
url = "https://github.com/ptiede/TransformVariables.jl"

[sources.VLBIImagePriors]
rev = "ptiede-reactantperf"
url = "https://github.com/ptiede/VLBIImagePriors.jl"

[sources.VLBILikelihoods]
rev = "ptiede-reactant"
url = "https://github.com/ptiede/VLBILikelihoods.jl"

[sources.VLBISkyModels]
rev = "ptiede-reactnfft"
url = "https://github.com/EHTJulia/VLBISkyModels.jl"
