[deps]
Boltz = "4544d5e4-abc5-4dea-817f-29e4c205d9c8"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[sources]
Reactant = {path = "../.."}

[compat]
Boltz = "1.7"
Chairmarks = "1"
Enzyme = "0.13.73"
JSON = "1"
Lux = "1.21"
NeuralOperators = "0.6.2"
Printf = "1.10"
Reactant = "0.2.161"
julia = "1.11"
