[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[sources]
Reactant = {path = "../.."}

[compat]
Oceananigans = "=0.99.2"
