[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[sources]
Reactant = {path = "../.."}

[compat]
Oceananigans = "=0.99.2"
