[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
BinaryBuilderBase = "7f725544-6523-48cd-82d1-3fa08ff4056e"

[compat]
Clang = "0.18"

[sources]
Clang = {url = "https://github.com/wsmoses/Clang.jl", rev = "patch-1"}
