name = "XProfUtils"
uuid = "2504a78c-b2aa-47de-9ed8-a71e5918f272"
authors = ["Avik Pal <avikpal@mit.edu>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
CondaPkg = "0.2.33"
JSON3 = "1.14.3"
PythonCall = "0.9.31"
Reactant = "0.2.189"
Setfield = "1.1.2"
Sockets = "1.11.0"
