[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[sources]
Reactant = {path = "../.."}

[compat]
ArgParse = "1.2"
JSON3 = "1"
Reactant = "0.2"
julia = "1.10"
